# Generated by Django 6.0 on 2025-12-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='self_description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Self Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='self_long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Self Long Description'),
        ),
    ]
