# Generated by Django 6.0 on 2025-12-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sitesettings_self_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.TextField(blank=True, help_text='SVG Code of icon for display', null=True, verbose_name='SVG Code of icon'),
        ),
    ]
