# Generated by Django 6.0 on 2025-12-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_technology_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotatingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Text to display in the typing animation (e.g., 'Python Developer')", max_length=200)),
                ('text_type', models.CharField(choices=[('hero', 'Hero Section Typing Text'), ('tagline', 'Tagline/Subtitle'), ('achievement', 'Achievement/Stat'), ('feature', 'Feature Highlight')], default='hero', help_text='Where this text will be used', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Order in which texts appear (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this text should be displayed')),
                ('delay_seconds', models.FloatField(default=2.0, help_text='How long to display this text before switching (in seconds)')),
                ('typing_speed', models.IntegerField(default=100, help_text='Typing speed in milliseconds per character')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rotating Text',
                'verbose_name_plural': 'Rotating Texts',
                'ordering': ['text_type', 'order', 'created_at'],
                'indexes': [models.Index(fields=['text_type', 'is_active', 'order'], name='accounts_ro_text_ty_f2d4cb_idx')],
            },
        ),
    ]
