# Generated by Django 6.0 on 2025-12-21 00:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rotatingtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=ckeditor.fields.RichTextField(verbose_name='Detailed Description'),
        ),
    ]
