# Generated by Django 6.0 on 2025-12-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sitesettings_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
