# Generated by Django 6.0 on 2025-12-24 19:30

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sitesettings_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=200, verbose_name='Institution Name')),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='education/logos/', verbose_name='Institution Logo')),
                ('institution_website', models.URLField(blank=True, null=True, verbose_name='Institution Website')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('degree', models.CharField(max_length=200, verbose_name='Degree/Qualification')),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True, verbose_name='Field of Study/Major')),
                ('education_type', models.CharField(choices=[('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD/Doctorate'), ('associate', 'Associate Degree'), ('diploma', 'Diploma'), ('certification', 'Certification'), ('course', 'Course/Training'), ('bootcamp', 'Coding Bootcamp')], default='bachelors', max_length=20, verbose_name='Education Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date/Graduation Date')),
                ('is_current', models.BooleanField(default=False, help_text='Check if currently enrolled', verbose_name='Currently Studying')),
                ('description', models.TextField(blank=True, help_text='Brief description of the program', null=True, verbose_name='Description')),
                ('grade_type', models.CharField(choices=[('gpa', 'GPA'), ('percentage', 'Percentage'), ('cgpa', 'CGPA'), ('grade', 'Letter Grade'), ('none', 'No Grade')], default='none', max_length=20, verbose_name='Grade Type')),
                ('grade_value', models.DecimalField(blank=True, decimal_places=2, help_text='e.g., 3.8 for GPA, 85 for percentage', max_digits=5, null=True, verbose_name='Grade Value')),
                ('grade_scale', models.DecimalField(blank=True, decimal_places=2, help_text='e.g., 4.0 for GPA scale, 100 for percentage scale', max_digits=5, null=True, verbose_name='Grade Scale')),
                ('grade_display', models.CharField(blank=True, help_text="How to display the grade (e.g., '3.8/4.0 GPA')", max_length=50, null=True, verbose_name='Grade Display')),
                ('achievements', models.JSONField(blank=True, default=list, help_text='List of achievements, awards, or honors', verbose_name='Achievements/Awards')),
                ('courses', models.JSONField(blank=True, default=list, help_text='List of relevant courses completed', verbose_name='Relevant Courses')),
                ('skills_learned', models.JSONField(blank=True, default=list, help_text='List of skills acquired during the program', verbose_name='Skills Learned')),
                ('thesis_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Thesis/Dissertation Title')),
                ('thesis_url', models.URLField(blank=True, null=True, verbose_name='Thesis URL/Link')),
                ('transcript_url', models.URLField(blank=True, null=True, verbose_name='Transcript URL')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Education')),
                ('order', models.IntegerField(default=0, help_text='Higher numbers appear first', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=200, verbose_name='Position/Role')),
                ('company', models.CharField(max_length=200, verbose_name='Company/Organization')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='experience/logos/', verbose_name='Company Logo')),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='Company Website')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('experience_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('volunteer', 'Volunteer')], default='full_time', max_length=20, verbose_name='Employment Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, help_text='Check if this is your current position', verbose_name='Currently Working Here')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Job Description')),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='List of key responsibilities and achievements', verbose_name='Key Responsibilities')),
                ('skills_gained', models.JSONField(blank=True, default=list, help_text='List of skills learned/developed', verbose_name='Skills Gained')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Experience')),
                ('order', models.IntegerField(default=0, help_text='Higher numbers appear first', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='related_experiences', to='accounts.project', verbose_name='Related Projects')),
                ('technologies', models.ManyToManyField(blank=True, related_name='experiences', to='accounts.technology', verbose_name='Technologies Used')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="e.g., 'Software Engineer Resume', 'Technical CV 2024'", max_length=200, verbose_name='Resume Title')),
                ('file', models.FileField(help_text='Upload your resume file (PDF, DOCX, etc.)', upload_to='resumes/', verbose_name='Resume File')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Plain Text'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='File Type')),
                ('resume_type', models.CharField(choices=[('current', 'Current Resume'), ('technical', 'Technical Resume'), ('creative', 'Creative Resume'), ('academic', 'Academic CV'), ('concise', 'One-Page Resume'), ('detailed', 'Detailed Resume'), ('cover_letter', 'Cover Letter')], default='current', max_length=20, verbose_name='Resume Type')),
                ('language', models.CharField(default='en', help_text="Language code (e.g., 'en', 'fr', 'es')", max_length=10, verbose_name='Language')),
                ('version', models.CharField(default='1.0', help_text="Resume version (e.g., '1.0', '2024-01')", max_length=20, verbose_name='Version')),
                ('is_primary', models.BooleanField(default=False, help_text='Set as the main/default resume', verbose_name='Primary Resume')),
                ('is_public', models.BooleanField(default=True, help_text='Allow public access to download/view', verbose_name='Publicly Accessible')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('file_size', models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='File Size (bytes)')),
                ('download_count', models.IntegerField(default=0, editable=False, verbose_name='Download Count')),
                ('view_count', models.IntegerField(default=0, editable=False, verbose_name='View Count')),
                ('description', models.TextField(blank=True, help_text='Brief description of this resume version', null=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (page count, creation date, etc.)', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('education', models.ManyToManyField(blank=True, related_name='resumes', to='accounts.education', verbose_name='Included Education')),
                ('experiences', models.ManyToManyField(blank=True, related_name='resumes', to='accounts.experience', verbose_name='Included Experiences')),
                ('projects', models.ManyToManyField(blank=True, related_name='resumes', to='accounts.project', verbose_name='Included Projects')),
                ('technologies', models.ManyToManyField(blank=True, related_name='resumes', to='accounts.technology', verbose_name='Included Technologies')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-is_primary', '-last_updated', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['is_current', 'is_featured', 'start_date'], name='accounts_ex_is_curr_404011_idx'),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('is_primary',), name='unique_primary_resume'),
        ),
    ]
