# Generated by Django 6.0 on 2025-12-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_education_experience_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='my_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/my_image/', verbose_name='MY_IMAGE'),
        ),
    ]
