# Generated by Django 6.0 on 2025-12-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_sitesettings_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='self_description',
            field=models.TextField(blank=True, null=True, verbose_name='Self Description'),
        ),
    ]
